### ISSUE TITLE
ionic cli subdependency issues

### ISSUE THREAD

**Issue by pghoratiu** [bitrise-steplib/steps-ionic-archive#54]
The original ionic cli package is deprecated (https://www.npmjs.com/package/ionic) replaced by **@ionic/cli** and due to a recent change to a sub-dependency the original version ionic@5.4.14 is no longer working as it should, when issuing 

`ionic --version`

it will print out the following error:

```
ionic --version
/usr/local/lib/node_modules/ionic/node_modules/@ionic/utils-fs/dist/index.js:168
exports.pathExists = pathExists;
                   ^

TypeError: Cannot set property pathExists of #<Object> which has only a getter
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/utils-fs/dist/index.js:168:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-framework/utils/node.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```
Which blocks the build process.

Relevant output from the build:

```
Config:
- Platform: android
- Configuration: release
- Target: device
- BuildConfig: ./build.json
- Options: --prod
- Username: 
- Password: 
- RunPrepare: false
- IonicVersion: 5.4.13
- CordovaVersion: 9.0.0
- WorkDir: src/mobile/[REDACTED]
- DeployDir: /Users/vagrant/deploy
- UseCache: false

Switch working directory to: /Users/vagrant/git/src/mobile/[REDACTED]
Js package manager used: npm

Updating cordova version to: 9.0.0

$ npm "remove" "cordova"


$ npm "install" "-g" "cordova@9.0.0"


Updating ionic version to: 5.4.13

$ npm "remove" "ionic"


$ npm "install" "-g" "ionic@5.4.13"


cordova version: 9.0.0
Failed to get ionic version, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ionic-archive@2.1.1 (exit code: 1)                                                    | 39.82 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...://github.com/bitrise-community/steps-ionic-archive/issues      |
| Source: https://github.com/bitrise-community/steps-ionic-archive                     |
+---+---------------------------------------------------------------+----------+
```

I think the solution would be to use the recomended npm package https://www.npmjs.com/package/@ionic/cli instead of the old one, I'm not aware of any backwards incompatibility issues.

**Comment by lpusok** [comment]
Hello @pghoratiu, @fubira,
There is a new version of ionic-archive available (https://github.com/bitrise-steplib/steps-ionic-archive/releases/tag/2.2.0), which installs `@ionic/cli` when selcting version 6 or `latest`.
